# Your Solution
version: '3'
services:
  book-catalog:
    image: book-catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://wendy_z68_user:GfVEPz2ql6bhJhOn06nrIPetMW86vlctNnR@pg-crv7ffdds78s7a9uheo-a.oregon-postgres.render.com/wendy_z68
    restart: "no"

  inventory-management:
    image: inventory-management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=postgresql://wendy_z68_user:GfVEPz2ql6bhJhOn06nrIPetMW86vlctNnR@pg-crv7ffdds78s7a9uheo-a.oregon-postgres.render.com/wendy_z68
    restart: "no"

